# For more info on HTTP files go to https://aka.ms/vs/httpfile
@url = https://localhost:7078/api
@servicdId = 2
POST {{url}}/reservations/{{servicdId}}

Content-Type: application/json

{
  "problemDescription": "their is a chair was broken and i want to fix it"
}

###
GET {{url}}/reservations/